### PR TITLE
convertBuffer(): clear duplex device outBuffer if outJump > inJump

### PR DESCRIPTION
**Pull request by MarcusTomlinson**
Resolves: https://github.com/thestk/rtaudio/issues/248

### CODE REVIEW

**Comment by MarcusTomlinson** [comment]
Hmm, so I get that the < was put here as an optimization, but I’m actually wondering if the original intention was >.

I.e. if outputs > inputs, clear the buffer.

This to me seems logical. It doesn’t matter if the device buffer has some output data still floating around in it when converting for user input as the user will only ever receive the channels he/she cares about.

As it stands now (if inputs > outputs), input data left behind in the device buffer after convertBuffer will always end up in the output.

**Comment by MarcusTomlinson** [comment]
Hmm, so I get that the < was put here as an optimization, but I’m actually wondering if the original intention was >.

I.e. if outputs > inputs, clear the buffer.

This to me seems logical. It doesn’t matter if the device buffer has some output data still floating around in it when converting for user input as the user will only ever receive the channels he/she cares about.

As it stands now (if outputs < inputs), input data left behind in the device buffer after convertBuffer will always end up in the output.

@radarsat1 & @garyscavone, does this logic make sense? Or can you recall a particular scenario where clearing the device buffer is needed for outputs < inputs?

**Comment by MarcusTomlinson** [comment]
Just pushed an even simpler, optimised solution to this:

**Clear the duplex device's output buffer if there are more device outputs than user outputs.**

Note that outJump will never be greater than inJump in the reverse direction (from device input to user input), as the user can't ask for more input channels than are physically available.

**Comment by radarsat1** [comment]
I'll leave this one for @garyscavone as i'm not very familiar with this part of the code.

**Comment by MarcusTomlinson** [comment]
@garyscavone, have you managed to have a look at this at all?

**Comment by garyscavone** [comment]
Your logic seems correct. I assume you have tested the change and it worked, so go ahead and commit it. If you can't do the commit for some reason, let me know and I will.

**Comment by MarcusTomlinson** [comment]
> Your logic seems correct. I assume you have tested the change and it worked, so go ahead and commit it. If you can't do the commit for some reason, let me know and I will.

Yeah, I've tested it. It certainly fixes the linked bug, and I've not seen any further regression caused. Thanks for the thumbs up, I'll merge.

**Pull request merged**
