### PR TITLE
No-exceptions branch

### PR DESCRIPTION
**Pull request by radarsat1**
This is @garyscavone's no-exceptions branch, updated to current master, that was well received in #212.  I propose to merge it now; it will affect current user code, so the other option is to wait until after the next release, but I prefer not to wait.  Open for comments, concerns about this idea.

### CODE REVIEW

**Comment by radarsat1** [comment]
I should add, I have looked it over once more and don't find egregious issues.  However, no guarantee that it's problem free, but in my experience there's no better way to find out except putting it on master and seeing who complains.  It will never get completely vetted by all interested parties until it's released, so no point waiting. (imho)  It's also getting harder to maintain a diverging branch, so.. already it's difficult to "diff" this with master to figure out what the overall changes are.

**Comment by radarsat1** [comment]
Note: this branch also contains a version bump.

**Comment by ntonnaett** [comment]
Shouldn't those functions be made noexcept now?

**Comment by garyscavone** [comment]
I know there are some bugs in this PR, particularly related to WASAPI, but I think it is easier to merge this first and then fix them after.

**Pull request merged**
