### PR TITLE
Add missing initialisation for CallbackInfo thread member

### PR DESCRIPTION
**Pull request by quicky2000**
Thread member of Callback Info structure is not initialised, add missing initialisation

### CODE REVIEW

**Comment by quicky2000** [comment]
Checks are failed on same point than master branch (lround method missing)

**Comment by quicky2000** [comment]
Hi, I rebased on master and now all checks are OK

**Comment by garyscavone** [comment]
I'll go ahead and merge this but RtAudio is primarily maintained through its own github repo. When a new STK release is made, the latest versions of RtAudio and RtMidi are simply copied to the STK distribution, over-writing older versions. So, it you want this change to be persistent, it should be made in the RtAudio github repo.

**Comment by garyscavone** [comment]
Oops ... ignore the previous comment!

**Comment by quicky2000** [comment]
OK, thanks !

**Pull request merged**
