### PR TITLE
refactor: convert line endings to unix format (LF)

### PR DESCRIPTION
**Pull request by antis81**
Converts line endings in RtAudio.cpp to cross-platform (Unix => LF) format.

**Important note:**
After merge/rebase onto master, probably every open PR will be in conflict state and has to be rebased onto master. Can we send a notification mail to all developers?

### CODE REVIEW

**Comment by speps** [comment]
I don't see the point, that should be done with Git options really.

**Comment by radarsat1** [comment]
I think this should be fixed, but I don't think this patch should be applied until immediately before a release.

**Comment by garyscavone** [comment]
I don't think RtAudio.cpp used to have CR line endings. Perhaps somewhere along the line, we made a commit that added them?

**Comment by radarsat1** [comment]
Regardless, this sorely needs to be done.. I think my last commit added one LF and now emacs loads the whole file with LF and the CRs are displayed.  Very weird.  (And sorry about that, I'll fix it.)

Instead of merging this however, I suggest simply running the whole source through dos2unix immediately before the next release.  There are relatively few pull requests right now so it's a good time.

**Comment by garyscavone** [comment]
Fixed in new release.

**Pull request closed without merging**
