### PR TITLE
Memory Leak using Alsa on Linux ( RtApiAlsa::probeDeviceOpen )

### LINKED ISSUE #228: Memory Leak using Alsa on Linux ( RtApiAlsa::probeDeviceOpen )
### RtAudio.cpp

in the RtApiAlsa::probeDeviceOpen (7529)

in the debug you attach the output to stderr

```c++
#if defined(__RTAUDIO_DEBUG__)
	snd_output_t *out;
	snd_output_stdio_attach(&out, stderr, 0);
#endif
```

But you don't release the output on the end of the method... each time you leak 16 to 24 bytes due to this attachment.

### Solution

 - before each return in this function put something like this:

```c++
#if defined(__RTAUDIO_DEBUG__)
//stops mem leak at debug
snd_output_close(out);
#endif
return FAILURE;
```

And finally you can return success with no leaks.

```c++
#if defined(__RTAUDIO_DEBUG__)
//stops mem leak at debug
snd_output_close(out);
#endif
return SUCCESS;
```

That's it.

### PR DESCRIPTION
**Pull request by A-Ribeiro**
Closes #228

### CODE REVIEW

**Comment by garyscavone** [comment]
Sorry it took so long to look at this. The proposed solution is rather repetitive. What about changing every "return FAILURE;" to "goto error;" and then add the check for DEBUG there? You'd also have to do a check before the "return SUCCESS;".

I don't have a Linux box handy to test this.

**Comment by A-Ribeiro** [comment]
Hi, 

i personally, don't like to use goto with cpp. 

but I agree that will be less code with this. 

i detected the leak using the libasan with sanitize address flag... the leak appeared in that point.

**Comment by radarsat1** [comment]
tested, thanks

**Comment by radarsat1** [comment]
By the way I had a brief look at the `goto` solution (which I like) but there are many instances of goto crossing initialization errors, e.g.

```
RtAudio.cpp:7881:15: note:   crosses initialization of ‘AlsaHandle* apiInfo’
   AlsaHandle *apiInfo = 0;
```

Then I came up with an RAII solution which is better, will push it now.

**Pull request merged**
