### PR TITLE
Fix Issue #69 - Allow non-default sample rates in WASAPI

### PR DESCRIPTION
**Pull request by MarcusTomlinson**
As WASAPI itself does not provide support for sample rates other than the current system default, I've introduced the Microsoft MFT (Media Foundation Transform) library into RtApiWasapi in order to allow users to specify the sample rate they wish to use.

### CODE REVIEW

**Comment by paulmasri** [comment]
@MarcusTomlinson FWIW Travis is complaining about 94dbbb2 (in case you didn't see it)

**Comment by MarcusTomlinson** [comment]
Hmm, I've only ever built RtAudio with VC++ (so all good there of course). Looks like I'll need to install MinGW and try to reproduce the build failure locally.

**Comment by KnappSas** [comment]
Hey @MarcusTomlinson .. Will there be some progress on this issue?

**Comment by MarcusTomlinson** [comment]
@KnappSas, unfortunately I've been swamped these last 2 months. I was actually thinking of asking if anyone was able and willing to assist me on this one. All builds fine on VS, I just haven't worked with MinGW much, so I'd need a good couple days to get set up and fix it myself.

**Comment by radarsat1** [comment]
It appears that the WASAPI headers in MingW define the same structs. (ksmedia.h and stfmif.h both define `struct tagTIMECODE_SAMPLE`

**Comment by radarsat1** [comment]
It could be a bug in MingW.  I haven't found anything in a search on the topic.
Anyways, if you want to reproduce I suggest using a Linux system or Docker instead of installing MingW on Windows, since that is the environment used by Travis.  It is not really necessary to support WASAPI on MingW/Linux, it is only used for testing on Travis, however it would be a shame to have to disable this configuration as it helps for testing that codepath.

**Comment by KnappSas** [comment]
@MarcusTomlinson On my local Windows 8.1 I wasn't able to build your stuff I'm afraid. 

> 1>c:\program files (x86)\windows kits\8.1\include\um\strmif.h(13490): error C2011: 'tagTIMECODE_SAMPLE': 'struct' type redefinition
1>c:\program files (x86)\windows kits\8.1\include\shared\ksmedia.h(5880): note: see declaration of 'tagTIMECODE_SAMPLE'
1>c:\program files (x86)\windows kits\8.1\include\um\ddraw.h(713): error C2011: '_DDPIXELFORMAT': 'struct' type redefinition
1>c:\program files (x86)\windows kits\8.1\include\shared\ksmedia.h(6361): note: see declaration of '_DDPIXELFORMAT'
1>c:\program files (x86)\windows kits\8.1\include\um\ddraw.h(2259): error C2079: '_DDSURFACEDESC::ddpfPixelFormat' uses undefined struct '_DDPIXELFORMAT'
1>c:\program files (x86)\windows kits\8.1\include\um\ddraw.h(2302): error C2079: '_DDSURFACEDESC2::ddpfPixelFormat' uses undefined struct '_DDPIXELFORMAT'

Any hint?

**Comment by radarsat1** [comment]
Oh interesting, that's very similar to the error from MingW, so maybe there are some headers that cannot go together here?  Or is there a global header that is supposed to be used instead?

**Comment by KnappSas** [comment]
What about this https://msdn.microsoft.com/en-us/library/windows/desktop/dd389294(v=vs.85).aspx ? 

>  [MFPlay is available for use in the operating systems specified in the Requirements section. It may be altered or unavailable in subsequent versions. ]

..and requirements say Windows 7.

**Comment by MarcusTomlinson** [comment]
This branch was building and running just fine in Visual Studio 2018 on my Windows 10 machine.

**Comment by radarsat1** [comment]
I believe you, but "works for me" is not really good enough, especially if it breaks things for Windows <10.  We need to figure out how to correctly detect if this feature is available and only turn it on under those circumstances.

**Comment by MarcusTomlinson** [comment]
Haha

**Comment by KnappSas** [comment]
I actually just build it via trial & error. I moved all Media Foundation includes up above audioclient.h. Unfortunately I now don't get any sound in the app where I'm using RtAudio :(

**Comment by radarsat1** [comment]
I just tried what you describe on MingW and it seems to help but I get,

```
RtAudio.cpp:4051:3: error: ‘IMFTransform’ does not name a type
```

so I added `#include <mftransform.h>` and then I get,

```
RtAudio.cpp:4054:3: error: ‘IWMResamplerProps’ does not name a type
```

but as far as I can tell [from here](https://msdn.microsoft.com/en-us/library/windows/desktop/ff819250(v=vs.85).aspx) this should be defined in `wmcodecdsp.h` which is definitely included.

So it seems maybe a way to detect if the necessary feature is available is to check defines in that include.
I found a Windows 7 copy of that file [here](https://searchcode.com/codesearch/view/66548741/)

and it seems we can check `#ifdef __IWMResamplerProps_FWD_DEFINED__`

**Comment by radarsat1** [comment]
Can we gate all the using WasapiResampler with,

```
#ifdef __WASAPI_ALLOW_NON_DEFAULT_SAMPLE_RATES__                                        
#endif
```

and define immediately after the includes,
```
#ifdef __IWMResamplerProps_FWD_DEFINED__                                                 
#define __WASAPI_ALLOW_NON_DEFAULT_SAMPLE_RATES__                                        
#endif 
```

**Comment by radarsat1** [comment]
Admittedly it's weird that IWMResamplerProps is not available in that header, since the doc page clearly says it's available since Windows XP, but I guess the Windows Media Foundation headers in MingW are not quite up to scratch, which is not a great reason to not include this patch.  I would just like to gate it with that preprocessor define so that the rest of the WASAPI support can be tested.

**Comment by paulmasri** [comment]
Just in case it's relevant, which versions of MinGW are each of you using? I'm curious why it compiles on one Win10 system and not another. I have definitely experienced issues with some versions of MinGW (when compiling my Qt app). Maybe this might help work out whether it's a MinGW issue or a repo issue.

**Comment by radarsat1** [comment]
I'm testing with mingw from Ubuntu 17.04:

```
$ x86_64-w64-mingw32-gcc --version
x86_64-w64-mingw32-gcc (GCC) 6.2.1 20161119
```

Although I think Travis uses an older version of Ubuntu, 14.04

**Comment by KnappSas** [comment]
So the audio issue for me was fixed. I opened a pull request for this in Marcus repository.

**Comment by KnappSas** [comment]
Hello,
I also tested it on Ubuntu 16.04 with the same result:
`x86_64-w64-mingw32-gcc (GCC) 5.3.1 20160211`

So would we consider the proposal from @radarsat1 using the preprocessor switches?

**Comment by MarcusTomlinson** [comment]
Thanks for the pointers guys. And sorry it took me so long to get back around to this!

I've managed to fix the build now. It was a combination of reordering includes, adding missing linker flags, and dodging some missing definitions in the mingw headers.

Looks all good to me now.

**Comment by MarcusTomlinson** [comment]
@radarsat1 you happy to merge this now?

**Comment by radarsat1** [comment]
Seems checks are passing so probably yes.  I haven't had time to review rtaudio/rtmidi stuff lately, so I'll have to get to it when I can.  Thanks for the contribution!

**Pull request merged**
